name: Clang-Tidy on PR Files Only

on:
  pull_request:
    paths:
      - 'src/**/*.cpp'
      - 'src/**/*.h'

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed to get full git history for diffing

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tidy cmake build-essential qt6-base-dev libqt6core6 libqt6gui6 libqt6widgets6 libssl-dev qt6-tools-dev qt6-tools-dev-tools libxkbcommon-dev libsodium-dev libvulkan-dev

    - name: Configure project with CMake
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Get list of changed C++ files
      id: changed-files
      run: |
        CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} | grep '^src/.*\.\(cpp\|h\)

    - name: Check if files were found
      if: steps.changed-files.outputs.RELATIVE_FILES == ''
      run: echo "No C++ files changed in this PR"

    - name: Run clang-tidy on changed files
      if: steps.changed-files.outputs.FILES != ''
      run: |
        cd build
        echo "Checking files: ${{ steps.changed-files.outputs.RELATIVE_FILES }}"
        clang-tidy -p . ${{ steps.changed-files.outputs.FILES }} > tidy-report.txt
        cat tidy-report.txt

    - name: Upload tidy report
      if: steps.changed-files.outputs.FILES != ''
      uses: actions/upload-artifact@v4
      with:
        name: clang-tidy-report
        path: build/tidy-report.txt

    - name: Comment PR with clang-tidy results
      if: steps.changed-files.outputs.FILES != '' && always()
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = 'build/tidy-report.txt';
          
          if (fs.existsSync(path)) {
            const report = fs.readFileSync(path, 'utf8');
            
            if (report.trim()) {
              const body = `## 🔍 Clang-Tidy Report
          
          \`\`\`
          ${report}
          \`\`\`
          
          <details>
          <summary>ℹ️ How to fix these issues</summary>
          
          Most clang-tidy issues can be automatically fixed by running:
          \`\`\`bash
          clang-tidy -p build --fix-errors ${{ steps.changed-files.outputs.FILES }}
          \`\`\`
          </details>`;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
              });
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '## ✅ Clang-Tidy Report\n\nNo issues found in the changed files!'
              });
            }
          } || true)
        if [ -n "$CHANGED_FILES" ]; then
          # Convert relative paths to absolute paths from project root
          ABSOLUTE_FILES=$(echo "$CHANGED_FILES" | sed "s|^|${{ github.workspace }}/|" | xargs)
          echo "FILES=$ABSOLUTE_FILES" >> $GITHUB_OUTPUT
          echo "RELATIVE_FILES=$CHANGED_FILES" >> $GITHUB_OUTPUT
        else
          echo "FILES=" >> $GITHUB_OUTPUT
          echo "RELATIVE_FILES=" >> $GITHUB_OUTPUT
        fi

    - name: Check if files were found
      if: steps.changed-files.outputs.FILES == ''
      run: echo "No C++ files changed in this PR"

    - name: Run clang-tidy on changed files
      if: steps.changed-files.outputs.FILES != ''
      run: |
        cd build
        echo "Checking files: ${{ steps.changed-files.outputs.FILES }}"
        clang-tidy -p . ${{ steps.changed-files.outputs.FILES }} > tidy-report.txt
        cat tidy-report.txt

    - name: Upload tidy report
      if: steps.changed-files.outputs.FILES != ''
      uses: actions/upload-artifact@v4
      with:
        name: clang-tidy-report
        path: build/tidy-report.txt

    - name: Comment PR with clang-tidy results
      if: steps.changed-files.outputs.FILES != '' && always()
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = 'build/tidy-report.txt';
          
          if (fs.existsSync(path)) {
            const report = fs.readFileSync(path, 'utf8');
            
            if (report.trim()) {
              const body = `## 🔍 Clang-Tidy Report
          
          \`\`\`
          ${report}
          \`\`\`
          
          <details>
          <summary>ℹ️ How to fix these issues</summary>
          
          Most clang-tidy issues can be automatically fixed by running:
          \`\`\`bash
          clang-tidy -p build --fix-errors ${{ steps.changed-files.outputs.FILES }}
          \`\`\`
          </details>`;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
              });
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '## ✅ Clang-Tidy Report\n\nNo issues found in the changed files!'
              });
            }
          }