name: Integration Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-server-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check server status
        run: |
          if ! curl -s -f https://rhudeboys.gobbler.info/status > /dev/null; then
            echo "::error::Server is offline"
            exit 1
          fi
        continue-on-error: false

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create file to test uploading
        run: echo "This is the contents of an encrypted file" > file.txt

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ pkg-config libssl-dev libsodium-dev qt6-base-dev qt6-tools-dev qt6-tools-dev-tools libsqlcipher-dev

      - name: Write .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Run integration test
        run: |
          cd build
          ctest -V -R IntegrationTests
