name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ pkg-config libssl-dev libsodium-dev qt6-base-dev qt6-tools-dev qt6-tools-dev-tools libsqlcipher-dev qt6-svg-dev libgtest-dev libopencv-dev
          sudo apt-get install -y libqt6core6 libqt6gui6 libqt6widgets6 libqt6uitools6 libqt6svg6

      - name: Write .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Configure CMake with debug symbols
        run: cmake -S . -B build -DCMAKE_VERBOSE_MAKEFILE=ON -DENABLE_DEBUG_SYMBOLS=ON -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build --config Debug --verbose

      - name: Run tests with core dump analysis
        run: |
          cd build
          # Enable core dumps
          ulimit -c unlimited
          echo "Core dump pattern: $(cat /proc/sys/kernel/core_pattern)"
          # Run tests with detailed output
          ctest --output-on-failure -R "EastwoodTests" -V || {
            echo "Test failed, checking for core dumps..."
            find . -name "core*" -exec ls -la {} \;
            exit 1
          }
