name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ pkg-config libssl-dev libsodium-dev qt6-base-dev qt6-tools-dev qt6-tools-dev-tools libsqlcipher-dev qt6-svg-dev libgtest-dev
          sudo apt-get install -y libqt6core6 libqt6gui6 libqt6widgets6 libqt6uitools6 libqt6svg6
          git clone https://github.com/nayuki/QR-Code-generator.git external/qrcodegen
          
          # Debug information
          echo "Checking libsodium installation:"
          pkg-config --cflags --libs libsodium
          ls -l /usr/include/sodium.h
          ls -l /usr/lib/x86_64-linux-gnu/libsodium*

      - name: Write .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_VERBOSE_MAKEFILE=ON
          cat build/CMakeFiles/CMakeOutput.log

      - name: Build
        run: cmake --build build --config Release --verbose

      - name: Run tests
        run: cd build && ctest --output-on-failure -R "EastwoodTests"
